name: taprobana_trails
description: Explore Sri Lanka's wonders with an all-in-one travel planning app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# App version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.5
  google_fonts: ^6.2.1
  intl: ^0.19.0
  equatable: ^2.0.5
  http: ^1.1.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.0
  connectivity_plus: ^6.1.3
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.14.3
  
  # Authentication
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^7.0.1
  
  # Database & Storage
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_crashlytics: ^4.3.5
  flutter_secure_storage: ^10.0.0-beta.4
  
  # State Management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  provider: ^6.0.5
  
  # UI Components
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  lottie: ^3.3.1
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.5.0
  fluttertoast: ^8.2.2
  sliding_up_panel: ^2.0.0+1
  carousel_slider: ^5.0.0
  pull_to_refresh: ^2.0.0
  photo_view: ^0.15.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.1
  
  # Maps & Location
  google_maps_flutter: ^2.4.0
  location: ^8.0.0
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  
  # AR (Augmented Reality)
  arcore_flutter_plugin: ^0.1.0  # For Android
  arkit_plugin: ^1.0.6  # For iOS
  
  # API Integrations
  dio: ^5.3.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  
  # Utilities
  permission_handler: ^12.0.0+1
  share_plus: ^10.1.4
  pdf: ^3.10.4
  flutter_local_notifications: ^14.0.0+1  
  image_cropper: ^9.1.0
  uuid: ^4.5.1
  logger: ^2.5.0
  timezone: ^0.10.1
  timeago: ^3.5.0
  collection: ^1.17.1
  country_picker: ^2.0.27
  percent_indicator: ^4.2.5
  table_calendar: ^3.1.3
  timeline_tile: ^2.0.0
  vector_math: ^2.1.4
  smooth_page_indicator: ^1.2.1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.9
  bloc_test: ^10.0.0
  mockito: ^5.4.2

# Flutter configuration
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  
# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"